### ISSUE TITLE
High memory consumption when using 'node2vec'.

### ISSUE THREAD

**Issue by wangjwchn** [snap-stanford/snap#140]
When I run `node2vec` on a directed graph with 1 million edges, it used about `40GB` memory. I want to run it on a larger graph, but i'm out of memory.  Is there any way to reduce memory consumption (such as batch processing)？

**Comment by minhlab** [comment]
I'm thinking we could try to use an unweighted graph similar to the [random walk example](https://github.com/snap-stanford/snap/blob/master/examples/randwalk/randwalk.cpp). It takes substantially less time to load and consumes 1/10 of RAM.

**Comment by celia01** [comment]
I meet the same problem with you. I also have two graph.
The smaller graph is：
142,000 Nodes
27,000,000 Edges
It's also used more than 100G memory.
This node2vec tools can’t support my lager graph, too.

**Comment by RemyLau** [comment]
@celia01 Hi, so it turns out that most of the overheads are from networkx, and node2vec trying to cache all the transition probabilities. I customized the implementation a little bit so that it computes the trans prob On The Fly. If you're interested in it, feel free to check it out! https://github.com/RemyLau/GraphUtil
I've done a couple benchmarking and the performance is pretty consistent with the original implementation. Just a side note, I had implemented multiple customization mode: FAST, OTF, NPOTF. OTF is the one you can try first, just specify --custom OTF when you call the n2v.py script

**Comment by roks** [comment]
node2vec requires significant amount of memory for graph of your size. Check out http://snap.stanford.edu/graphsage/ for a less memory demanding solution.

**Comment by wangjwchn** [comment]
@roks Cool, I'll try this one. 👍
