### ISSUE TITLE
Installation problems: Fatal Python error: PyThreadState_Get: no current thread

### ISSUE THREAD

**Issue by matteomanca** [snap-stanford/snap#88]
Dear all,

I'm trying to install snap for python (https://snap.stanford.edu/snappy/index.html) on my mac OSX but I get the following error:

"Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6"

Any idea?
Thanks in advance.

Matteo

**Comment by roks** [comment]
Please check out the following document:
https://docs.google.com/document/d/1ODvtQsJgiTOJH4-qBqwa6eAvoNJoiALqnk2pxFf1IzY/edit

**Comment by TomsonZeng** [comment]
This is caused by linking a static version of libpython into ycmd's ycm_core.so. This leads to multiple copies of the python interpreter loaded when python loads ycmd_core.so and this messes up python's global state. The details aren't important.

The solution is that the version of Python linked and run against must be built with either --enable-shared or --enable-framework (on OS X). This is achieved as follows (NOTE: for Mac, replace --enable-shared with --enable-framework):

When building python from source: ./configure --enable-shared {options}
When building python from pyenv: PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install {version}
